-- VHDL netlist generated by SCUBA Diamond_3.0_Production (94)
-- Module  Version: 3.4
--/home/soft/lattice/diamond/3.0_x64/ispfpga/bin/lin64/scuba -w -n random_size -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5c00 -type lfsr -stage 15 -feedback_poly 00 -init_seed 01 -parallel_out -e 

-- Mon May  5 15:21:23 2014

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity random_size is
    port (
        Clk: in  std_logic; 
        Enb: in  std_logic; 
        Rst: in  std_logic; 
        Dout: out  std_logic_vector(14 downto 0));
end random_size;

architecture Structure of random_size is

    -- internal signal declarations
    signal scuba_vlo: std_logic;
    signal lfsr_oddparity: std_logic;
    signal lfsr_reg_out0: std_logic;
    signal lfsr_reg_out1: std_logic;
    signal lfsr_reg_out2: std_logic;
    signal lfsr_reg_out3: std_logic;
    signal lfsr_reg_out4: std_logic;
    signal lfsr_reg_out5: std_logic;
    signal lfsr_reg_out6: std_logic;
    signal lfsr_reg_out7: std_logic;
    signal lfsr_reg_out8: std_logic;
    signal lfsr_reg_out9: std_logic;
    signal lfsr_reg_out10: std_logic;
    signal lfsr_reg_out11: std_logic;
    signal lfsr_reg_out12: std_logic;
    signal lfsr_reg_out14: std_logic;
    signal lfsr_reg_out13: std_logic;

    -- local component declarations
    component FD1P3IX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3JX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    LUT4_0: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>scuba_vlo, AD2=>scuba_vlo, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>lfsr_oddparity);

    FF_14: FD1P3JX
        port map (D=>lfsr_oddparity, SP=>Enb, CK=>Clk, PD=>Rst, 
            Q=>lfsr_reg_out0);

    FF_13: FD1P3IX
        port map (D=>lfsr_reg_out0, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out1);

    FF_12: FD1P3IX
        port map (D=>lfsr_reg_out1, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out2);

    FF_11: FD1P3IX
        port map (D=>lfsr_reg_out2, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out3);

    FF_10: FD1P3IX
        port map (D=>lfsr_reg_out3, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out4);

    FF_9: FD1P3IX
        port map (D=>lfsr_reg_out4, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out5);

    FF_8: FD1P3IX
        port map (D=>lfsr_reg_out5, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out6);

    FF_7: FD1P3IX
        port map (D=>lfsr_reg_out6, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out7);

    FF_6: FD1P3IX
        port map (D=>lfsr_reg_out7, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out8);

    FF_5: FD1P3IX
        port map (D=>lfsr_reg_out8, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out9);

    FF_4: FD1P3IX
        port map (D=>lfsr_reg_out9, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out10);

    FF_3: FD1P3IX
        port map (D=>lfsr_reg_out10, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out11);

    FF_2: FD1P3IX
        port map (D=>lfsr_reg_out11, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out12);

    FF_1: FD1P3IX
        port map (D=>lfsr_reg_out12, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out13);

    FF_0: FD1P3IX
        port map (D=>lfsr_reg_out13, SP=>Enb, CK=>Clk, CD=>Rst, 
            Q=>lfsr_reg_out14);

    Dout(0) <= lfsr_reg_out0;
    Dout(1) <= lfsr_reg_out1;
    Dout(2) <= lfsr_reg_out2;
    Dout(3) <= lfsr_reg_out3;
    Dout(4) <= lfsr_reg_out4;
    Dout(5) <= lfsr_reg_out5;
    Dout(6) <= lfsr_reg_out6;
    Dout(7) <= lfsr_reg_out7;
    Dout(8) <= lfsr_reg_out8;
    Dout(9) <= lfsr_reg_out9;
    Dout(10) <= lfsr_reg_out10;
    Dout(11) <= lfsr_reg_out11;
    Dout(12) <= lfsr_reg_out12;
    Dout(13) <= lfsr_reg_out13;
    Dout(14) <= lfsr_reg_out14;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of random_size is
    for Structure
        for all:FD1P3IX use entity ecp3.FD1P3IX(V); end for;
        for all:FD1P3JX use entity ecp3.FD1P3JX(V); end for;
        for all:ROM16X1A use entity ecp3.ROM16X1A(V); end for;
        for all:VLO use entity ecp3.VLO(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
